#%RAML 1.0 NamedExample
value:
  -
    partner: uber
    source: bhugaon
    destination: vimannagar
    city: pune
    typeOfCar: mini
    noOfSeats: 4
    price: 100
  
  -
    partner: ola
    source: whitefield
    destination: kundalhalli
    city: bangalore
    typeOfCar: primeSedan
    noOfSeats: 6
    price: 300 
