#%RAML 1.0 Library
usage: traits and datatypes for bookMyHoliday

traits:
  client_id_secret_trait:
    headers:
      client_id: string
      client_secret: string

  error_responses_trait:
    responses:
      400:
        body:
          application/json:
            type: object
            properties:
              error_type: string
              error_description: string
            example: {
              error_type: Bad Request,
              error_description: Invalid Input
            }
      401:
        body:
          application/json:
            type: object
            properties:
              error_type: string
              error_description: string
            example: {
              error_type: Unauthorized request,
              error_description: Invalid Credentials
            }
      404:
        body:
          application/json:
            type: object
            properties:
              error_type: string
              error_description: string
            example: {
              error_type: Resource Not Found,
              error_description: Resource Not Found
            }
      405:
        body:
          application/json:
            type: object
            properties:
              error_type: string
              error_description: string
            example: {
              error_type: Method Not Found,
              error_description: Method Not Found
            }
      500:
        body:
          application/json:
            type: object
            properties:
              error_type: string
              error_description: string
            example: {
              error_type: Internal Server Error,
              error_description: Internal Server Error
            }

types:
  get_carbooking_response_datatype:
    type: object
    properties:
      partner: string
      source: string
      destination: string
      city: string
      typeOfCar: string
      noOfSeats: integer
      price:
        type: number
        format: double
  
  post_carbooking_request_datatype:
    type: object
    properties:
      source: string
      destination: string
      firstName: string
      lastName: string
      city: string
      typeOfCar: string
      noOfSeats: integer
  
  post_carbooking_response_datatype:
    type: object
    properties:
      message: string
      carBookingDetails:
        type: object
        properties:
          partner: string
          source: string
          destination: string
          firstname: string
          lastname: string
          NoOfSeats: integer
          price:
            type: number
            format: double
          scheduledDate: date-only
          scheduledTime: time-only



